global using ServiceCenter.Domain.Core.Bases;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Linq.Expressions;
global using System.Threading;
global using System.Threading.Tasks;
global using ServiceCenter.Application.Services.Base;
global using ServiceCenter.Application.Utilities.Exceptions;